"""Parameter recovery tests for task-based DCM (REC-01).

Validates that Pyro SVI inference correctly recovers known ground-truth
connectivity parameters (A matrix) from synthetic BOLD data generated by
the task-DCM simulator. Tests use the simulate -> infer -> compare protocol.

CI-fast tests verify the pipeline works correctly (loss decreases, posterior
extractable, no NaN) on a few quick datasets. Strict recovery thresholds
(RMSE < 0.05, coverage in [0.80, 0.99], correlation > 0.85) are tested
in slow validation tests that use longer simulation and more SVI steps.

Task DCM SVI is computationally expensive due to ODE integration in each
SVI step (~1-2s/step on CPU for 3-region networks). CI tests use reduced
parameters for feasibility.

References
----------
[REF-001] Friston, Harrison & Penny (2003), Eq. 1.
[REF-002] Stephan et al. (2007), Eq. 2-6.
"""

from __future__ import annotations

import pytest
import torch
import pyro

from pyro_dcm.forward_models.neural_state import parameterize_A
from pyro_dcm.models import (
    task_dcm_model,
    create_guide,
    run_svi,
    extract_posterior_params,
)
from pyro_dcm.simulators.task_simulator import (
    make_block_stimulus,
    make_random_stable_A,
    simulate_task_dcm,
)


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _pearson_corr(x: torch.Tensor, y: torch.Tensor) -> float:
    """Pearson correlation between two 1D tensors.

    Manual implementation to avoid numpy.corrcoef process abort on
    Windows (see STATE.md decision).

    Parameters
    ----------
    x : torch.Tensor
        First 1D tensor.
    y : torch.Tensor
        Second 1D tensor of same length.

    Returns
    -------
    float
        Pearson correlation coefficient.
    """
    x_mean = x.mean()
    y_mean = y.mean()
    xd = x - x_mean
    yd = y - y_mean
    num = (xd * yd).sum()
    denom = (xd.pow(2).sum() * yd.pow(2).sum()).sqrt()
    if denom < 1e-15:
        return 0.0
    return (num / denom).item()


def compute_rmse_A(
    A_true: torch.Tensor, A_inferred: torch.Tensor,
) -> float:
    """RMSE between true and inferred A matrices.

    Parameters
    ----------
    A_true : torch.Tensor
        Ground-truth A matrix, shape ``(N, N)``.
    A_inferred : torch.Tensor
        Inferred A matrix, shape ``(N, N)``.

    Returns
    -------
    float
        Root mean squared error.
    """
    return torch.sqrt(torch.mean((A_true - A_inferred) ** 2)).item()


def _build_A_ci(
    A_free_lo: torch.Tensor,
    A_free_hi: torch.Tensor,
    N: int,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Convert A_free quantile bounds to parameterized A bounds.

    For off-diagonal: identity transform, bounds pass through.
    For diagonal: a_ii = -exp(A_free_ii)/2 is monotone decreasing,
    so lower/upper swap: A_lo_diag = -exp(A_free_hi_diag)/2,
    A_hi_diag = -exp(A_free_lo_diag)/2.

    Parameters
    ----------
    A_free_lo : torch.Tensor
        Lower bound (2.5th percentile) of A_free, shape ``(N, N)``.
    A_free_hi : torch.Tensor
        Upper bound (97.5th percentile) of A_free, shape ``(N, N)``.
    N : int
        Number of regions.

    Returns
    -------
    tuple of torch.Tensor
        (A_lo, A_hi) each shape ``(N, N)`` in parameterized A space.
    """
    diag_mask = torch.eye(N, dtype=torch.bool)

    A_lo = A_free_lo.clone()
    A_hi = A_free_hi.clone()

    # Diagonal: flip because -exp(x)/2 is decreasing
    A_lo[diag_mask] = -torch.exp(A_free_hi[diag_mask]) / 2.0
    A_hi[diag_mask] = -torch.exp(A_free_lo[diag_mask]) / 2.0

    return A_lo, A_hi


def run_single_task_recovery(
    seed: int,
    n_regions: int = 3,
    num_steps: int = 1000,
    duration: float = 90.0,
    n_blocks: int = 3,
) -> dict | None:
    """Run a single task-DCM parameter recovery trial.

    Generates synthetic BOLD data with known A, runs SVI inference,
    and compares inferred A to ground truth. Disables Pyro validation
    to handle NaN gracefully (caught as NaN ELBO by run_svi).

    Parameters
    ----------
    seed : int
        Random seed for reproducibility.
    n_regions : int, optional
        Number of brain regions. Default 3.
    num_steps : int, optional
        Number of SVI steps. Default 1000.
    duration : float, optional
        Simulation duration in seconds. Default 90.0.
    n_blocks : int, optional
        Number of stimulus blocks. Default 3.

    Returns
    -------
    dict or None
        Recovery result dict with keys A_true, A_inferred, A_lo, A_hi,
        losses, final_loss. Returns None if SVI fails.
    """
    try:
        N = n_regions
        M = 1  # single input

        # Disable Pyro validation to let NaN propagate to ELBO check
        pyro.enable_validation(False)

        # Generate ground truth A
        A_true = make_random_stable_A(N, density=0.5, seed=seed)

        # C: only region 0 receives input
        C = torch.zeros(N, M, dtype=torch.float64)
        C[0, 0] = 1.0

        # Stimulus
        stim = make_block_stimulus(
            n_blocks=n_blocks,
            block_duration=15.0,
            rest_duration=15.0,
            n_inputs=M,
        )

        # Simulate BOLD
        sim_result = simulate_task_dcm(
            A_true, C, stim,
            duration=duration, dt=0.01, TR=2.0, SNR=5.0,
            seed=seed,
        )

        # Build model args
        a_mask = torch.ones(N, N, dtype=torch.float64)
        c_mask = torch.zeros(N, M, dtype=torch.float64)
        c_mask[0, 0] = 1.0  # match C nonzero pattern

        dt_model = 0.5
        t_eval = torch.arange(
            0, duration, dt_model, dtype=torch.float64,
        )
        TR = 2.0

        model_args = (
            sim_result["bold"],
            sim_result["stimulus"],
            a_mask,
            c_mask,
            t_eval,
            TR,
            dt_model,
        )

        # Set seeds for reproducibility
        pyro.set_rng_seed(seed)
        torch.manual_seed(seed)

        # Create guide and run SVI
        guide = create_guide(task_dcm_model, init_scale=0.01)
        svi_result = run_svi(
            task_dcm_model, guide, model_args,
            num_steps=num_steps, lr=0.005,
            clip_norm=10.0, lr_decay_factor=0.01,
        )

        # Extract posterior
        posterior = extract_posterior_params(guide, model_args)
        A_free_median = posterior["median"]["A_free"]
        A_inferred = parameterize_A(A_free_median)

        # Get 95% CI via quantiles
        quantiles = guide.quantiles([0.025, 0.975], *model_args)
        A_free_lo = quantiles["A_free"][0]
        A_free_hi = quantiles["A_free"][1]

        # Convert to parameterized A bounds
        A_lo, A_hi = _build_A_ci(A_free_lo, A_free_hi, N)

        return {
            "A_true": A_true,
            "A_inferred": A_inferred,
            "A_lo": A_lo,
            "A_hi": A_hi,
            "losses": svi_result["losses"],
            "final_loss": svi_result["final_loss"],
        }

    except (RuntimeError, ValueError, AssertionError):
        # NaN ELBO, ODE blow-up, Pyro validation, or dopri5 underflow
        return None
    finally:
        pyro.enable_validation(True)


def compute_coverage(results_list: list[dict]) -> float:
    """Compute 95% CI coverage across recovery trials.

    For each result, checks element-wise whether A_true falls within
    [A_lo, A_hi]. Returns the fraction of all (dataset, element) pairs
    that are covered.

    Parameters
    ----------
    results_list : list of dict
        Each dict has A_true, A_lo, A_hi tensors.

    Returns
    -------
    float
        Fraction of elements where true value falls within 95% CI.
    """
    covered = 0
    total = 0
    for r in results_list:
        in_ci = (r["A_true"] >= r["A_lo"]) & (r["A_true"] <= r["A_hi"])
        covered += in_ci.sum().item()
        total += in_ci.numel()
    return covered / total if total > 0 else 0.0


# ---------------------------------------------------------------------------
# CI-fast tests: pipeline validation
# ---------------------------------------------------------------------------


class TestTaskDCMRecovery:
    """Task DCM parameter recovery -- CI-fast tests (REC-01).

    Validates that the SVI inference pipeline produces reasonable
    results on a small number of quick trials. Strict recovery
    thresholds are enforced in the slow validation tests.

    Uses 2 datasets x 200 SVI steps x 30s simulation to keep
    CI runtime under 5 minutes.
    """

    @pytest.fixture(scope="class")
    def quick_results(self) -> list[dict]:
        """Run 2 quick task DCM recovery trials."""
        results = []
        for seed in [100, 103]:
            result = run_single_task_recovery(
                seed=seed, n_regions=3, num_steps=200,
                duration=30.0, n_blocks=2,
            )
            if result is not None:
                results.append(result)
        return results

    def test_task_dcm_svi_completes(
        self, quick_results: list[dict],
    ) -> None:
        """SVI completes without NaN on at least 1 of 2 datasets."""
        assert len(quick_results) >= 1, (
            "All task DCM SVI runs failed (NaN/diverged)"
        )

    def test_task_dcm_loss_decreases(
        self, quick_results: list[dict],
    ) -> None:
        """ELBO loss decreases during SVI optimization."""
        assert len(quick_results) >= 1, "No successful runs"
        for i, r in enumerate(quick_results):
            losses = r["losses"]
            n = len(losses)
            n_fifth = max(n // 5, 1)
            first_20 = sum(losses[:n_fifth]) / n_fifth
            last_20 = sum(losses[-n_fifth:]) / n_fifth
            print(
                f"  Run {i}: first_20%={first_20:.1f}, "
                f"last_20%={last_20:.1f}"
            )
            assert last_20 < first_20, (
                f"Run {i}: loss did not decrease"
            )

    def test_task_dcm_posterior_finite(
        self, quick_results: list[dict],
    ) -> None:
        """Inferred A matrix contains only finite values."""
        assert len(quick_results) >= 1, "No successful runs"
        for r in quick_results:
            assert torch.isfinite(r["A_inferred"]).all(), (
                "NaN/Inf in inferred A matrix"
            )

    def test_task_dcm_diagonal_negative(
        self, quick_results: list[dict],
    ) -> None:
        """Inferred A diagonal is negative (self-inhibition)."""
        assert len(quick_results) >= 1, "No successful runs"
        for r in quick_results:
            diag = torch.diagonal(r["A_inferred"])
            assert (diag < 0).all(), (
                f"Non-negative diagonal in A: {diag}"
            )


# ---------------------------------------------------------------------------
# Slow validation: strict recovery thresholds
# ---------------------------------------------------------------------------


class TestTaskDCMRecoverySlow:
    """Task DCM parameter recovery -- slow validation tests.

    Strict thresholds with sufficient data and SVI convergence.
    Each test runs independently without shared fixtures.
    """

    @pytest.mark.slow
    def test_task_dcm_recovery_10_datasets(self) -> None:
        """10 datasets, 3 regions, 1000 steps, 90s duration.

        Validates RMSE < 0.05, coverage in [0.80, 0.99],
        correlation > 0.85.
        """
        results = []
        for seed in range(100, 110):
            result = run_single_task_recovery(
                seed=seed, n_regions=3, num_steps=1000,
                duration=90.0, n_blocks=3,
            )
            if result is not None:
                results.append(result)
                rmse = compute_rmse_A(
                    result["A_true"], result["A_inferred"],
                )
                print(f"  seed={seed}: RMSE={rmse:.4f}")
            else:
                print(f"  seed={seed}: FAILED")

        assert len(results) >= 5, (
            f"Too few runs: {len(results)}/10"
        )

        # RMSE
        rmses = [
            compute_rmse_A(r["A_true"], r["A_inferred"])
            for r in results
        ]
        mean_rmse = sum(rmses) / len(rmses)
        print(f"Mean RMSE: {mean_rmse:.4f}")
        assert mean_rmse < 0.05, (
            f"Mean RMSE {mean_rmse:.4f} >= 0.05"
        )

        # Coverage
        coverage = compute_coverage(results)
        print(f"Coverage: {coverage:.4f}")
        assert 0.80 <= coverage <= 0.99, (
            f"Coverage {coverage:.4f} not in [0.80, 0.99]"
        )

        # Correlation
        all_true = torch.cat(
            [r["A_true"].flatten() for r in results]
        )
        all_inferred = torch.cat(
            [r["A_inferred"].flatten() for r in results]
        )
        corr = _pearson_corr(all_true, all_inferred)
        print(f"Correlation: {corr:.4f}")
        assert corr > 0.85, f"Correlation {corr:.4f} <= 0.85"

    @pytest.mark.slow
    def test_task_dcm_recovery_50_datasets_3_regions(self) -> None:
        """50 datasets, 3 regions, 3000 steps, 300s duration."""
        results = []
        for seed in range(200, 250):
            result = run_single_task_recovery(
                seed=seed, n_regions=3, num_steps=3000,
                duration=300.0, n_blocks=5,
            )
            if result is not None:
                results.append(result)

        assert len(results) >= 30, (
            f"Too few runs: {len(results)}/50"
        )

        rmses = [
            compute_rmse_A(r["A_true"], r["A_inferred"])
            for r in results
        ]
        mean_rmse = sum(rmses) / len(rmses)
        assert mean_rmse < 0.05, f"RMSE {mean_rmse:.4f} >= 0.05"

        coverage = compute_coverage(results)
        assert 0.80 <= coverage <= 0.99, (
            f"Coverage {coverage:.4f} not in [0.80, 0.99]"
        )

        all_true = torch.cat(
            [r["A_true"].flatten() for r in results]
        )
        all_inferred = torch.cat(
            [r["A_inferred"].flatten() for r in results]
        )
        corr = _pearson_corr(all_true, all_inferred)
        assert corr > 0.85, f"Correlation {corr:.4f} <= 0.85"

    @pytest.mark.slow
    def test_task_dcm_recovery_5_regions(self) -> None:
        """10 datasets, 5 regions, 3000 steps, 300s duration."""
        results = []
        for seed in range(300, 310):
            result = run_single_task_recovery(
                seed=seed, n_regions=5, num_steps=3000,
                duration=300.0, n_blocks=5,
            )
            if result is not None:
                results.append(result)

        assert len(results) >= 5, (
            f"Too few runs: {len(results)}/10"
        )

        rmses = [
            compute_rmse_A(r["A_true"], r["A_inferred"])
            for r in results
        ]
        mean_rmse = sum(rmses) / len(rmses)
        assert mean_rmse < 0.05, f"RMSE {mean_rmse:.4f} >= 0.05"

        coverage = compute_coverage(results)
        assert 0.80 <= coverage <= 0.99, (
            f"Coverage {coverage:.4f} not in [0.80, 0.99]"
        )

        all_true = torch.cat(
            [r["A_true"].flatten() for r in results]
        )
        all_inferred = torch.cat(
            [r["A_inferred"].flatten() for r in results]
        )
        corr = _pearson_corr(all_true, all_inferred)
        assert corr > 0.85, f"Correlation {corr:.4f} <= 0.85"
