"""Parameter recovery tests for spectral DCM (REC-02).

Validates that Pyro SVI inference correctly recovers known ground-truth
connectivity parameters (A matrix) from synthetic CSD data generated by
the spectral DCM simulator. Tests use the simulate -> infer -> compare
protocol.

Metrics:
- RMSE(A) < 0.05 averaged over 10 synthetic 3-region datasets
- 95% CI coverage in [0.80, 0.99] for A matrix elements
- Correlation(A_true, A_inferred) > 0.85

Note: Coverage range is [0.80, 0.99] rather than [0.90, 0.99] due to
known mean-field VI underdispersion (AutoNormal ignores posterior
correlations between A, noise_a, noise_b, noise_c parameters). See
RESEARCH.md Pitfall 1.

References
----------
[REF-010] Friston, Kahan, Biswal & Razi (2014). A DCM for resting
    state fMRI. NeuroImage, 94, 396-407. Eq. 3-10.
"""

from __future__ import annotations

import pytest
import torch
import pyro

from pyro_dcm.forward_models.neural_state import parameterize_A
from pyro_dcm.models import (
    spectral_dcm_model,
    create_guide,
    run_svi,
    extract_posterior_params,
)
from pyro_dcm.models.spectral_dcm_model import decompose_csd_for_likelihood
from pyro_dcm.simulators.spectral_simulator import (
    make_stable_A_spectral,
    simulate_spectral_dcm,
)


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _pearson_corr(x: torch.Tensor, y: torch.Tensor) -> float:
    """Pearson correlation between two 1D tensors.

    Manual implementation to avoid numpy.corrcoef process abort on
    Windows (see STATE.md decision).

    Parameters
    ----------
    x : torch.Tensor
        First 1D tensor.
    y : torch.Tensor
        Second 1D tensor of same length.

    Returns
    -------
    float
        Pearson correlation coefficient.
    """
    x_mean = x.mean()
    y_mean = y.mean()
    xd = x - x_mean
    yd = y - y_mean
    num = (xd * yd).sum()
    denom = (xd.pow(2).sum() * yd.pow(2).sum()).sqrt()
    if denom < 1e-15:
        return 0.0
    return (num / denom).item()


def compute_rmse_A(
    A_true: torch.Tensor, A_inferred: torch.Tensor,
) -> float:
    """RMSE between true and inferred A matrices.

    Parameters
    ----------
    A_true : torch.Tensor
        Ground-truth A matrix, shape ``(N, N)``.
    A_inferred : torch.Tensor
        Inferred A matrix, shape ``(N, N)``.

    Returns
    -------
    float
        Root mean squared error.
    """
    return torch.sqrt(torch.mean((A_true - A_inferred) ** 2)).item()


def _build_A_ci(
    A_free_lo: torch.Tensor,
    A_free_hi: torch.Tensor,
    N: int,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Convert A_free quantile bounds to parameterized A bounds.

    For off-diagonal: identity transform, bounds pass through.
    For diagonal: a_ii = -exp(A_free_ii)/2 is monotone decreasing,
    so lower/upper swap: A_lo_diag = -exp(A_free_hi_diag)/2,
    A_hi_diag = -exp(A_free_lo_diag)/2.

    Parameters
    ----------
    A_free_lo : torch.Tensor
        Lower bound (2.5th percentile) of A_free, shape ``(N, N)``.
    A_free_hi : torch.Tensor
        Upper bound (97.5th percentile) of A_free, shape ``(N, N)``.
    N : int
        Number of regions.

    Returns
    -------
    tuple of torch.Tensor
        (A_lo, A_hi) each shape ``(N, N)`` in parameterized A space.
    """
    diag_mask = torch.eye(N, dtype=torch.bool)

    A_lo = A_free_lo.clone()
    A_hi = A_free_hi.clone()

    # Diagonal: flip because -exp(x)/2 is decreasing
    A_lo[diag_mask] = -torch.exp(A_free_hi[diag_mask]) / 2.0
    A_hi[diag_mask] = -torch.exp(A_free_lo[diag_mask]) / 2.0

    return A_lo, A_hi


def run_single_spectral_recovery(
    seed: int,
    n_regions: int = 3,
    num_steps: int = 500,
    snr: float = 10.0,
) -> dict | None:
    """Run a single spectral DCM parameter recovery trial.

    Generates synthetic CSD with known A, adds noise at the specified
    SNR, runs SVI inference, and compares inferred A to ground truth.

    Parameters
    ----------
    seed : int
        Random seed for reproducibility.
    n_regions : int, optional
        Number of brain regions. Default 3.
    num_steps : int, optional
        Number of SVI steps. Default 500 (calibrated for coverage).
    snr : float, optional
        Signal-to-noise ratio for CSD noise. Default 10.0.

    Returns
    -------
    dict or None
        Recovery result dict with keys A_true, A_inferred, A_lo, A_hi,
        losses, final_loss. Returns None if SVI fails.
    """
    try:
        N = n_regions

        # Generate ground truth A
        A_true = make_stable_A_spectral(N, seed=seed)

        # Simulate CSD
        sim = simulate_spectral_dcm(
            A_true, TR=2.0, n_freqs=32, seed=seed,
        )

        # Add noise to CSD in decomposed real/imag space
        obs_real = decompose_csd_for_likelihood(sim["csd"])
        signal_power = obs_real.pow(2).mean().sqrt()
        noise_std = signal_power / snr
        torch.manual_seed(seed + 1000)
        noisy_obs = obs_real + noise_std * torch.randn_like(obs_real)

        # Reconstruct noisy complex CSD
        F, n, _ = sim["csd"].shape
        half = F * n * n
        noisy_real = noisy_obs[:half].reshape(F, n, n)
        noisy_imag = noisy_obs[half:].reshape(F, n, n)
        noisy_csd = torch.complex(noisy_real, noisy_imag)

        # Build model args
        a_mask = torch.ones(N, N, dtype=torch.float64)
        model_args = (noisy_csd, sim["freqs"], a_mask, N)

        # Set seeds for reproducibility
        pyro.set_rng_seed(seed)
        torch.manual_seed(seed)

        # Create guide and run SVI
        guide = create_guide(spectral_dcm_model, init_scale=0.01)
        svi_result = run_svi(
            spectral_dcm_model, guide, model_args,
            num_steps=num_steps, lr=0.01,
            clip_norm=10.0, lr_decay_factor=0.1,
        )

        # Extract posterior
        posterior = extract_posterior_params(guide, model_args)
        A_free_median = posterior["median"]["A_free"]
        A_inferred = parameterize_A(A_free_median)

        # Get 95% CI via quantiles
        quantiles = guide.quantiles([0.025, 0.975], *model_args)
        A_free_lo = quantiles["A_free"][0]
        A_free_hi = quantiles["A_free"][1]

        # Convert to parameterized A bounds
        A_lo, A_hi = _build_A_ci(A_free_lo, A_free_hi, N)

        return {
            "A_true": A_true,
            "A_inferred": A_inferred,
            "A_lo": A_lo,
            "A_hi": A_hi,
            "losses": svi_result["losses"],
            "final_loss": svi_result["final_loss"],
        }

    except (RuntimeError, ValueError):
        # NaN ELBO or Pyro validation error
        return None


def compute_coverage(results_list: list[dict]) -> float:
    """Compute 95% CI coverage across recovery trials.

    For each result, checks element-wise whether A_true falls within
    [A_lo, A_hi]. Returns the fraction of all (dataset, element) pairs
    that are covered.

    Parameters
    ----------
    results_list : list of dict
        Each dict has A_true, A_lo, A_hi tensors.

    Returns
    -------
    float
        Fraction of elements where true value falls within 95% CI.
    """
    covered = 0
    total = 0
    for r in results_list:
        in_ci = (r["A_true"] >= r["A_lo"]) & (r["A_true"] <= r["A_hi"])
        covered += in_ci.sum().item()
        total += in_ci.numel()
    return covered / total if total > 0 else 0.0


# ---------------------------------------------------------------------------
# Module-level cache fixture for CI-fast tests
# ---------------------------------------------------------------------------


_SPECTRAL_RESULTS: list[dict] | None = None


@pytest.fixture(scope="module")
def spectral_recovery_results() -> list[dict]:
    """Run 10 spectral DCM recovery trials and cache results.

    Uses seeds 100-109, 3 regions, 500 SVI steps, SNR=10 noise.
    Results are cached at module level to avoid redundant SVI runs.

    Returns
    -------
    list of dict
        Successful recovery results (None entries filtered out).
    """
    global _SPECTRAL_RESULTS  # noqa: PLW0603

    if _SPECTRAL_RESULTS is not None:
        return _SPECTRAL_RESULTS

    results = []
    for seed in range(100, 110):
        result = run_single_spectral_recovery(
            seed=seed, n_regions=3, num_steps=500, snr=10.0,
        )
        if result is not None:
            results.append(result)
            rmse_val = compute_rmse_A(
                result["A_true"], result["A_inferred"],
            )
            print(f"  seed={seed}: RMSE={rmse_val:.4f}")
        else:
            print(f"  seed={seed}: FAILED (NaN/diverged)")

    _SPECTRAL_RESULTS = results
    return results


# ---------------------------------------------------------------------------
# CI-fast tests (10 datasets, 3 regions)
# ---------------------------------------------------------------------------


class TestSpectralDCMRecovery:
    """Spectral DCM parameter recovery -- CI-fast tests (REC-02)."""

    def test_spectral_dcm_rmse_below_threshold(
        self, spectral_recovery_results: list[dict],
    ) -> None:
        """RMSE(A) < 0.05 averaged over 10 synthetic 3-region datasets."""
        results = spectral_recovery_results
        assert len(results) >= 8, (
            f"Too few successful runs: {len(results)}/10"
        )

        rmses = [
            compute_rmse_A(r["A_true"], r["A_inferred"])
            for r in results
        ]
        mean_rmse = sum(rmses) / len(rmses)

        print(f"\nSpectral DCM RMSE results ({len(results)} runs):")
        for i, rmse in enumerate(rmses):
            print(f"  Run {i}: RMSE = {rmse:.4f}")
        print(f"  Mean RMSE = {mean_rmse:.4f}")

        assert mean_rmse < 0.05, (
            f"Mean RMSE {mean_rmse:.4f} >= 0.05 threshold"
        )

    def test_spectral_dcm_coverage_calibrated(
        self, spectral_recovery_results: list[dict],
    ) -> None:
        """95% CI coverage in [0.80, 0.99] for A matrix elements.

        Lower bound is 0.80 instead of 0.90 due to known mean-field VI
        underdispersion (AutoNormal ignores posterior correlations
        between A and noise parameters).
        """
        results = spectral_recovery_results
        assert len(results) >= 8, (
            f"Too few successful runs: {len(results)}/10"
        )

        coverage = compute_coverage(results)
        print(f"\nSpectral DCM coverage: {coverage:.4f}")

        if coverage < 0.80:
            for i, r in enumerate(results):
                in_ci = (
                    (r["A_true"] >= r["A_lo"])
                    & (r["A_true"] <= r["A_hi"])
                )
                n_covered = in_ci.sum().item()
                n_total = in_ci.numel()
                print(
                    f"  Run {i}: {n_covered}/{n_total} covered"
                )

        assert 0.80 <= coverage <= 0.99, (
            f"Coverage {coverage:.4f} not in [0.80, 0.99]"
        )

    def test_spectral_dcm_correlation_high(
        self, spectral_recovery_results: list[dict],
    ) -> None:
        """Correlation(A_true, A_inferred) > 0.85 across all runs."""
        results = spectral_recovery_results
        assert len(results) >= 8, (
            f"Too few successful runs: {len(results)}/10"
        )

        all_true = torch.cat([r["A_true"].flatten() for r in results])
        all_inferred = torch.cat(
            [r["A_inferred"].flatten() for r in results]
        )

        corr = _pearson_corr(all_true, all_inferred)
        print(f"\nSpectral DCM overall correlation: {corr:.4f}")

        assert corr > 0.85, (
            f"Correlation {corr:.4f} <= 0.85 threshold"
        )

    def test_spectral_dcm_loss_decreases(
        self, spectral_recovery_results: list[dict],
    ) -> None:
        """ELBO loss decreases for at least 8 of 10 runs."""
        results = spectral_recovery_results
        assert len(results) >= 8, (
            f"Too few successful runs: {len(results)}/10"
        )

        converged = 0
        for i, r in enumerate(results):
            losses = r["losses"]
            n = len(losses)
            n_fifth = max(n // 5, 1)
            first_20_pct = sum(losses[:n_fifth]) / n_fifth
            last_20_pct = sum(losses[-n_fifth:]) / n_fifth
            did_converge = last_20_pct < first_20_pct
            if did_converge:
                converged += 1
            print(
                f"  Run {i}: first_20%={first_20_pct:.1f}, "
                f"last_20%={last_20_pct:.1f}, "
                f"converged={did_converge}"
            )

        print(f"\nConverged: {converged}/{len(results)}")
        assert converged >= 8, (
            f"Only {converged}/{len(results)} converged (need >= 8)"
        )


# ---------------------------------------------------------------------------
# Slow validation tests (50 datasets, 5-region)
# ---------------------------------------------------------------------------


class TestSpectralDCMRecoverySlow:
    """Spectral DCM parameter recovery -- slow validation tests."""

    @pytest.mark.slow
    def test_spectral_dcm_recovery_50_datasets(self) -> None:
        """50 datasets, 3 regions, 3000 steps. Full validation."""
        results = []
        for seed in range(200, 250):
            result = run_single_spectral_recovery(
                seed=seed, n_regions=3, num_steps=3000, snr=10.0,
            )
            if result is not None:
                results.append(result)

        assert len(results) >= 40, (
            f"Too few successful runs: {len(results)}/50"
        )

        rmses = [
            compute_rmse_A(r["A_true"], r["A_inferred"])
            for r in results
        ]
        mean_rmse = sum(rmses) / len(rmses)
        assert mean_rmse < 0.05, f"Mean RMSE {mean_rmse:.4f} >= 0.05"

        coverage = compute_coverage(results)
        assert 0.80 <= coverage <= 0.99, (
            f"Coverage {coverage:.4f} not in [0.80, 0.99]"
        )

        all_true = torch.cat([r["A_true"].flatten() for r in results])
        all_inferred = torch.cat(
            [r["A_inferred"].flatten() for r in results]
        )
        corr = _pearson_corr(all_true, all_inferred)
        assert corr > 0.85, f"Correlation {corr:.4f} <= 0.85"

    @pytest.mark.slow
    def test_spectral_dcm_recovery_5_regions(self) -> None:
        """10 datasets, 5 regions, 3000 steps."""
        results = []
        for seed in range(300, 310):
            result = run_single_spectral_recovery(
                seed=seed, n_regions=5, num_steps=3000, snr=10.0,
            )
            if result is not None:
                results.append(result)

        assert len(results) >= 8, (
            f"Too few successful runs: {len(results)}/10"
        )

        rmses = [
            compute_rmse_A(r["A_true"], r["A_inferred"])
            for r in results
        ]
        mean_rmse = sum(rmses) / len(rmses)
        assert mean_rmse < 0.05, f"Mean RMSE {mean_rmse:.4f} >= 0.05"

        coverage = compute_coverage(results)
        assert 0.80 <= coverage <= 0.99, (
            f"Coverage {coverage:.4f} not in [0.80, 0.99]"
        )

        all_true = torch.cat([r["A_true"].flatten() for r in results])
        all_inferred = torch.cat(
            [r["A_inferred"].flatten() for r in results]
        )
        corr = _pearson_corr(all_true, all_inferred)
        assert corr > 0.85, f"Correlation {corr:.4f} <= 0.85"
